### ISSUE TITLE
DRP can't override mod datapacks

### ISSUE THREAD

**Issue by Partonetrain** [DarkRoleplay/DRP---Global-Data-Pack#1]
DRP-GDP doesn't seem to be able to override datapacks being added by other mods. 

SilentGear adds its own datapack, like so: https://github.com/SilentChaos512/Silent-Gear/tree/1.14/src/main/resources/data
It also lets you change its datapacks with your own datapacks: https://github.com/SilentChaos512/Silent-Gear/wiki/Gear-Parts

However, I can't seem to override them using GlobalDataPacks, while the vanilla method of dropping the data pack in your save seems to work fine.

for example, placing a datapack using SilentGear's in my save works as intented, like so:
saves\t12\datapacks\testdata\data\silentgear\silentgear\parts\main\gold.json
but placing it in global_data_packs like this does not act the same:
global_data_packs\testdata\data\silentgear\silentgear\parts\main\gold.json

The datapack between the two folders is the same, .mcmeta and everything.

(May be an issue with silent gear, not sure)

**Comment by JTK222** [comment]
Hm... that will be difficult to figure out :thinking:
Sadly you can either put your datapack when adding it ingame to the bottom, or top.
Top would override datapacks that are in the world folder. Bottom has the issue you described.
But yes, I guess there will be less users adding custom data packs when they are using modpacks.
So I'll switch that.

**Comment by JTK222** [comment]
Uploaded a new version https://www.curseforge.com/minecraft/mc-mods/drp-global-datapack/files/2781689 (waiting for approval at the time I am writing this)
hopefully it does fix this issue, I'd appreciate if you could test it.

**Comment by Partonetrain** [comment]
Unfortunately that seems to have broken it entirely :(
Got an warning on the title screen with this new version:
![image](https://user-images.githubusercontent.com/19861808/64575225-4f164680-d338-11e9-8eb5-a463fcbd15ee.png)

and datapacks in global_data_packs folder don't show up after using /datapack list

**Comment by JTK222** [comment]
Sometimes I hate my life 🙄
It took just 2 hours to find the issue, just another dumb copy paste issue xD
Fixed in 0.2.1

**Comment by Partonetrain** [comment]
Looks to work correctly now! Thank you.
